-- ==============================================================================
-- Metis Supabase Schema: In-App Ratings & Anonymous Installation Telemetry
-- Target Version: v0.3.0+
-- Description: Database tables and indexes to track user ratings, feedback,
--              version distribution, and installation metrics per release/edition.
-- ==============================================================================

-- 1. In-App User Ratings and Feedback Table
create table if not exists public.app_ratings (
  id bigint generated by default as identity primary key,
  installation_id text not null,
  version text not null default '0.3.0',         -- App version e.g. '0.3.0'
  build_variant text not null default 'bundle',  -- Build edition: 'bundle' | 'lite'
  platform text not null default '',             -- Operating system: 'win32' | 'darwin' | 'linux'
  arch text not null default '',                 -- Architecture: 'x64' | 'arm64'
  rating integer not null check (rating >= 1 and rating <= 7),
  feeling text not null default '',              -- Feeling label e.g. 'Delighted', 'Satisfied'
  comment text not null default '',              -- Optional user text feedback
  timestamp timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

-- Indexes for performance & analytics grouping by version, build variant, and rating
create index if not exists idx_app_ratings_version on public.app_ratings (version);
create index if not exists idx_app_ratings_build_variant on public.app_ratings (build_variant);
create index if not exists idx_app_ratings_version_variant on public.app_ratings (version, build_variant);
create index if not exists idx_app_ratings_rating on public.app_ratings (rating);
create index if not exists idx_app_ratings_installation_id on public.app_ratings (installation_id);
create index if not exists idx_app_ratings_created_at_desc on public.app_ratings (created_at desc);

-- 2. One-Time Anonymous Desktop Installation Pings Table
create table if not exists public.app_installations (
  id bigint generated by default as identity primary key,
  installation_id text not null unique,          -- Unique random local installation UUID
  version text not null default '0.3.0',         -- App version e.g. '0.3.0'
  build_variant text not null default 'bundle',  -- Build edition: 'bundle' | 'lite'
  platform text not null default '',             -- Operating system: 'win32' | 'darwin' | 'linux'
  arch text not null default '',                 -- Architecture: 'x64' | 'arm64'
  r_status text not null default '',             -- 'bundled_ok' | 'system_r_found' | 'r_missing'
  system_memory_gb numeric(5, 2),               -- System RAM in GB
  country text not null default '',              -- Inferred server-side from request IP headers
  created_at timestamptz not null default timezone('utc', now())
);

-- Indexes for installation analytics per release and platform
create index if not exists idx_app_installs_version on public.app_installations (version);
create index if not exists idx_app_installs_build_variant on public.app_installations (build_variant);
create index if not exists idx_app_installs_version_variant on public.app_installations (version, build_variant);
create index if not exists idx_app_installs_country on public.app_installations (country);
create index if not exists idx_app_installs_created_at_desc on public.app_installations (created_at desc);

-- Views for analytics summaries
create or replace view public.view_ratings_by_version as
select
  version,
  build_variant,
  count(*) as total_ratings,
  round(avg(rating), 2) as avg_rating,
  count(*) filter (where rating >= 5) as positive_ratings
from public.app_ratings
group by version, build_variant
order by version desc, build_variant;

create or replace view public.view_installations_by_version as
select
  version,
  build_variant,
  platform,
  count(*) as total_installs
from public.app_installations
group by version, build_variant, platform
order by version desc, total_installs desc;

-- 3. GitHub release assets are the canonical download counter.
-- GitHub increments download_count for both website clicks and direct GitHub
-- downloads, so this table stores the synchronized per-asset source of truth.
create table if not exists public.release_download_assets (
  id bigint generated by default as identity primary key,
  version text not null,
  build_variant text not null check (build_variant in ('bundle', 'lite')),
  platform text not null check (platform in ('windows', 'mac-arm', 'mac-intel')),
  asset_name text not null,
  github_asset_url text not null,
  sha256 text not null default '',
  github_download_count bigint not null default 0 check (github_download_count >= 0),
  website_click_count bigint not null default 0 check (website_click_count >= 0),
  github_synced_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  unique (version, asset_name),
  unique (version, platform, build_variant)
);

create index if not exists idx_release_download_assets_version
  on public.release_download_assets (version);
create index if not exists idx_release_download_assets_platform_variant
  on public.release_download_assets (version, platform, build_variant);

-- 0.3.0 catalog: keep these names and URLs identical to the GitHub release.
insert into public.release_download_assets
  (version, build_variant, platform, asset_name, github_asset_url, sha256)
values
  ('0.3.0', 'bundle', 'windows', 'metis.0.3.0.Bundle.exe', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Bundle.exe', 'ba05d8fc270f464ef86b64d2acd6a552c1d36b1be7cfc0ebc8b920e0cb6feedf'),
  ('0.3.0', 'lite', 'windows', 'metis.0.3.0.Lite.exe', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Lite.exe', '4e63920d6dfd5c7504574004846e7597b717816710fd623e7a58dad306087224'),
  ('0.3.0', 'bundle', 'mac-arm', 'metis.0.3.0.Bundle.macOS.arm64.dmg', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Bundle.macOS.arm64.dmg', '2b2d56f20bb99f87177cb29624bf4a1414b4f064ee416dd470ff692ad3e13ef6'),
  ('0.3.0', 'bundle', 'mac-intel', 'metis.0.3.0.Bundle.macOS.x64.dmg', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Bundle.macOS.x64.dmg', 'cd9c172200a2e9594e85faf4cb5bc36109721647489f43279aea21760133b7ad'),
  ('0.3.0', 'lite', 'mac-arm', 'metis.0.3.0.Lite.macOS.arm64.dmg', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Lite.macOS.arm64.dmg', '124e6b1577de73541e38ccb49f62e9a22f039baa66c033a9261f90b3259ea9b7'),
  ('0.3.0', 'lite', 'mac-intel', 'metis.0.3.0.Lite.macOS.x64.dmg', 'https://github.com/aar0ndaniel/metis-app/releases/download/0.3.0/metis.0.3.0.Lite.macOS.x64.dmg', 'd642f603a74821c890bb2e81a7c69c86025b6c745285189ddd6758968f9d9790')
on conflict (version, asset_name) do update set
  build_variant = excluded.build_variant,
  platform = excluded.platform,
  github_asset_url = excluded.github_asset_url,
  sha256 = excluded.sha256,
  updated_at = timezone('utc', now());

-- Website events remain useful for diagnostics, but are not added to the
-- GitHub count because the same user may also download directly from GitHub.
create table if not exists public.release_download_events (
  id bigint generated by default as identity primary key,
  version text not null,
  build_variant text not null check (build_variant in ('bundle', 'lite')),
  platform text not null check (platform in ('windows', 'mac-arm', 'mac-intel')),
  asset_name text not null,
  asset_url text not null,
  source text not null default 'website' check (source in ('website', 'github')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_release_download_events_asset
  on public.release_download_events (version, platform, build_variant, created_at desc);

create or replace view public.view_download_counts as
select
  version,
  platform,
  build_variant,
  asset_name,
  github_asset_url,
  github_download_count as total_downloads,
  github_download_count,
  website_click_count,
  github_synced_at
from public.release_download_assets
order by version desc, platform, build_variant;

create or replace function public.sync_github_release_asset_download_count(
  p_version text,
  p_asset_name text,
  p_download_count bigint,
  p_synced_at timestamptz default timezone('utc', now())
) returns void
language sql
security definer
set search_path = public
as $$
  update public.release_download_assets
  set github_download_count = greatest(p_download_count, 0),
      github_synced_at = p_synced_at,
      updated_at = timezone('utc', now())
  where version = p_version and asset_name = p_asset_name;
$$;
