import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const workspaceRoot = path.resolve(__dirname, '..')

async function read(relativePath) {
  return fs.readFile(path.join(workspaceRoot, relativePath), 'utf8')
}

const titleBar = await read('src/components/TitleBar.tsx')
const app = await read('src/App.tsx')
const resultsView = await read('src/pages/ResultsView.tsx')
const preferences = await read('src/components/PreferencesModal.tsx')
const onboardingTour = await read('src/components/OnboardingTour.tsx')
const whatsNewModal = await read('src/components/WhatsNewModal.tsx')
const tarkModal = await read('src/components/TarkModal.tsx')
const tarkIcon = await read('src/components/TarkIcon.tsx')
const tarkPreview = await read('src/pages/TarkPreview.tsx')
const tarkReportTables = await read('src/utils/tarkReportTables.ts')

assert.doesNotMatch(tarkIcon, /tark icon\.png/, 'TarkIcon should not depend on the removed PNG asset.')
assert.match(tarkIcon, />\s*T\s*<\/span>/, 'TarkIcon should render the inline Tark mark.')
assert.match(titleBar, /\{ label: 'Tark it', items: buildTarkMenu\(\), width: 220 \},\s*\n\s*\{ label: 'Help'/, 'TitleBar should expose Tark as a top-level menu before Help.')
assert.doesNotMatch(titleBar, /\bSparkle\b/, 'TitleBar should not use the old sparkle icon for Tark.')
assert.match(titleBar, /menu\.label === 'Tark it' \? 'tour-tark'/, 'TitleBar should expose the Tark menu tab as the tour target.')
assert.match(titleBar, /action: 'open-tark'/, 'TitleBar Tark button should dispatch the global open-tark action.')
assert.doesNotMatch(titleBar, /TARK_TITLEBAR_PHRASES|useTypingCycle|prefers-reduced-motion: reduce|tark-titlebar-caret/, 'TitleBar Tark should not use typing animation.')
assert.doesNotMatch(titleBar, /id="tour-tark"/, 'TitleBar should not keep the old separate Tark button near the window controls.')
assert.doesNotMatch(titleBar, /Tark journal-ready report/, 'TitleBar should not keep the old separate Tark button tooltip.')
assert.doesNotMatch(titleBar, /id="tour-preferences"/, 'Preferences should not keep the titlebar tour/icon slot.')
assert.doesNotMatch(titleBar, /<Gear[\s\S]*title="Preferences"/, 'Preferences gear should not remain as a visible titlebar button.')
const editMenuSource = titleBar.slice(titleBar.indexOf('function buildEditMenu'), titleBar.indexOf('function buildViewMenu'))
assert.match(editMenuSource, /label: 'Preferences'[\s\S]*action: 'open-preferences'/, 'Preferences should remain available from the Edit menu.')

assert.match(app, /import TarkModal from '\.\/components\/TarkModal'/, 'App should import the Tark modal.')
assert.match(app, /import TarkPreview from '\.\/pages\/TarkPreview'/, 'App should keep the legacy Tark preview route as a fallback surface.')
assert.match(app, /const \[tarkOpen,\s*setTarkOpen\]\s*=\s*useState\(false\)/, 'App should own Tark modal visibility.')
assert.match(app, /action === 'open-tark'[\s\S]*setTarkOpen\(true\)/, 'Global actions should open Tark.')
assert.doesNotMatch(app, /function handleTarkIt/, 'App should not own the old preview CTA handler.')
assert.doesNotMatch(app, /navigate\(`\/tark-preview\/\$\{request\.workspaceId\}\/\$\{request\.modelId\}`/, 'Tark CTA should no longer open the copy/paste preview route.')
assert.match(app, /<Route path="\/tark-preview\/:workspaceId\/:modelId" element=\{<TarkPreview \/>/, 'App should register the Tark preview route.')
assert.match(app, /<TarkModal[\s\S]*workspaces=\{workspaces\}[\s\S]*activeWorkspaceId=\{activeWorkspaceId\}/, 'Tark modal should receive workspace context.')
assert.doesNotMatch(app, /onTarkIt=\{handleTarkIt\}/, 'Tark modal should own Word export instead of handing a preview request to App.')
assert.doesNotMatch(app.slice(app.indexOf('{tarkOpen &&'), app.indexOf('{quitConfirmOpen &&')), /onOpenModel/, 'Tark modal should not expose a duplicate Open model action.')

assert.match(tarkModal, /function SelectBox/, 'Tark modal should use the same custom dropdown feel as PLS-style modals.')
assert.match(tarkModal, /FileText/, 'Tark modal should use the built-in report icon.')
assert.doesNotMatch(tarkModal, /\bSparkle\b/, 'Tark modal should not use the old sparkle icon.')
assert.match(tarkModal, /border: '1px solid var\(--color-border\)'/, 'Tark fields should use the shared bordered field style.')
assert.doesNotMatch(tarkModal, /type="radio"/, 'Tark modal should remove the old construct-label radio controls.')
assert.match(tarkModal, /type="checkbox"/, 'Tark modal should include PLS-style checkbox controls.')
assert.match(tarkModal, /Report title/, 'Tark modal should include an editable report title.')
assert.match(tarkModal, /const TARK_LABEL_COLOR = 'var\(--color-text-secondary\)'/, 'Tark modal labels should use the same neutral text color as the modal heading.')
assert.match(tarkModal, /const TARK_CONTROL_TEXT_COLOR = 'var\(--color-text-secondary-alt\)'/, 'Tark modal control text should use the neutral grey token.')
assert.match(tarkModal, />\s*Tark report\s*<\/span>/, 'Tark modal heading should say Tark report.')
assert.match(tarkModal, /useState\('Tark report'\)/, 'Tark report title should default to Tark report.')
assert.match(tarkModal, /placeholder="Tark report title"/, 'Tark title input should use Tark report language.')
assert.doesNotMatch(tarkModal, /Tark journal report/, 'Tark modal heading should not say journal report.')
assert.match(tarkModal, /const TARK_STEPS = \['Report setup', 'Path diagram', 'Word document'\]/, 'Tark modal should use the approved three-step Word export flow.')
assert.match(tarkModal, /color: TARK_LABEL_COLOR/, 'Tark modal field and section labels should use the heading text color.')
assert.match(tarkModal, /color: selected \? TARK_CONTROL_TEXT_COLOR : TARK_CONTROL_MUTED_COLOR/, 'Tark dropdown selected text should use grey control text.')
assert.match(tarkModal, /accentColor: 'var\(--color-accent\)'/, 'Tark checkbox controls should use the active accent color.')
assert.match(tarkModal, /Include path diagram/, 'Tark modal should expose the path diagram option.')
assert.match(tarkModal, /Include advanced analyses/, 'Tark modal should allow advanced analyses to be optional.')
assert.match(tarkModal, /height: 410[\s\S]*maxHeight: 'calc\(100vh - 32px\)'/, 'Tark modal should use the compact Permutation/MGA shell height.')
assert.doesNotMatch(tarkModal, /TableFamilyList|Journal table families|Default table families|Advanced table families|getTarkTableFamilies/, 'Tark modal should not show the journal table-family explainer block.')
assert.match(tarkModal, /Structural paths/, 'Tark modal should expose structural-path diagram settings.')
assert.doesNotMatch(tarkModal, /function DiagramSelectField/, 'Diagram controls should not use the staggered side-label arrangement.')
assert.match(tarkModal, /Indicator paths/, 'Tark modal should expose indicator-path diagram settings.')
assert.doesNotMatch(tarkModal, /Construct labels|Full construct names in tables|Abbreviations everywhere/, 'Tark modal should remove preview-era construct-name controls.')
assert.match(tarkModal, /File name/, 'Tark modal should expose a Word file-name field.')
assert.match(tarkModal, /Save location/, 'Tark modal should expose a Word save-location picker.')
assert.match(tarkModal, /Create Tark report/, 'Tark primary action should create the Word document.')
assert.match(tarkModal, /buildTarkReportDocxBase64/, 'Tark primary action should build a native Word package.')
assert.match(tarkModal, /writeFile\(\{[\s\S]*encoding: 'base64'/, 'Tark primary action should save the .docx through the secure bridge.')
assert.doesNotMatch(tarkModal, /previewNotice|Tark found the saved results/, 'Tark modal should not show the removed fake preview notice.')
assert.doesNotMatch(tarkModal, /<SectionTitle>Requirements<\/SectionTitle>/, 'Tark modal should not duplicate model requirements outside the model dropdown.')
assert.doesNotMatch(tarkModal, /<SectionTitle>Readiness<\/SectionTitle>|<SectionTitle>Summary<\/SectionTitle>/, 'Tark modal should not show the removed side readiness or summary rail.')
assert.doesNotMatch(tarkModal, /Open model|Preview report/, 'Tark modal should not show old footer actions.')
assert.doesNotMatch(tarkModal, /function RequirementPill|REQUIRED_RESULTS/, 'Tark modal should not render the old readiness pills.')

assert.match(resultsView, /import\s*\{\s*ResultChart(?:\s*,\s*buildChartSvgForPanel)?\s*\}\s*from\s*'\.\.\/components\/ResultsCharts'/, 'ResultsView should use charts only for the approved results panels.')
assert.match(resultsView, /analysisMode === 'advanced'/, 'ResultsView should keep inline charts scoped to Advanced Analysis.')
assert.match(resultsView, /PLSPREDICT_ERROR_HISTOGRAM_PANELS = \['plsem-mv-error-hist', 'plsem-lv-error-hist'\]/, 'ResultsView should keep the PLSpredict error histogram charts.')
assert.match(resultsView, /isPlsPredictErrorHistogram\(selectedPanel\)/, 'ResultsView should keep histogram chart rendering scoped through the histogram helper.')
assert.match(resultsView, /DOWNLOADABLE_RESULT_CHART_PANELS/, 'ResultsView should expose export controls for the supported result charts.')
assert.doesNotMatch(resultsView, /resultsChartPreferences/, 'ResultsView should not keep chart preference state.')
assert.match(resultsView, /buildChartSvgForPanel[\s\S]*navigator\.clipboard[\s\S]*image\/svg\+xml/, 'ResultsView should expose copy and download actions for chart SVGs.')
assert.doesNotMatch(preferences, /Include charts in report/, 'Preferences should not expose chart export settings for launch.')

assert.match(whatsNewModal, /title: 'Tark reports'/, 'The 0.3.0 update carousel should introduce Tark before the action-led walkthrough.')
assert.match(whatsNewModal, /tark-report\.png/, 'The Tark update should show a real in-app capture.')
assert.match(whatsNewModal, /https:\/\/metis\.emend\.it\.com\/tark-report\.html/, 'The Tark update should link to the report guide.')
assert.doesNotMatch(onboardingTour, /selector: '#tour-feedback'/, 'The action-led walkthrough should not point to the removed feedback titlebar button.')
assert.doesNotMatch(onboardingTour, /selector: '#tour-preferences'|App Preferences/, 'Onboarding tour should not point users at the old Preferences titlebar icon.')

assert.doesNotMatch(tarkPreview, /function PreviewPill|<PreviewPill|Report setup|Construct labels/, 'Tark preview should not show setup or construct-label summary cards.')
assert.match(tarkPreview, /import PathDiagram from '\.\.\/components\/PathDiagram'/, 'Tark preview should render the path diagram when requested.')
assert.match(tarkPreview, /const \[diagramCollapsed,\s*setDiagramCollapsed\]\s*=\s*useState\(true\)/, 'Tark preview path diagram should be collapsed by default.')
assert.match(tarkPreview, /aria-expanded=\{!diagramCollapsed\}/, 'Tark preview should expose the diagram collapsed/expanded state.')
assert.match(tarkPreview, /setDiagramCollapsed\(\(collapsed\) => !collapsed\)/, 'Tark preview should allow opening and collapsing the path diagram.')
assert.match(tarkPreview, /onClick=\{\(\) => copySections\(tableSections, request\.reportTitle\)\}/, 'Copy all should copy only the Tark report tables.')
assert.doesNotMatch(tarkPreview, /copyTarkReport|buildDiagramClipboardHtml|normalizeDiagramSvgForClipboard|renderDiagramSvgToPngDataUrl|diagramPng|image\/png|leadingHtml: options\.diagramHtml|leadingText: options\.diagramText/, 'Tark copy-all should not copy, rasterize, or include the path diagram.')
assert.match(tarkPreview, /buildTarkReportSections\(request, savedAnalyses, savedModel\)/, 'Tark preview should use the tested report-table builder.')
assert.match(tarkPreview, /buildTarkDiagramResults\(savedAnalyses, savedModel\)/, 'Tark preview should build diagram overlays from saved PLS values.')
assert.match(tarkPreview, /child\.state\?\.modelSnapshot\?\.constructs/, 'Tark preview should prefer the result model snapshot for path diagrams.')
assert.doesNotMatch(tarkPreview, /function buildMeasurementSection|function buildStructuralSection|function buildModelFitSection/, 'Tark preview should not keep stale inline table parsers.')
assert.match(tarkReportTables, /includes\('htmt'\)/, 'Tark discriminant table should filter to HTMT rows only.')
assert.match(tarkReportTables, /readValue\(row, \['row_name', 'row', 'Construct', 'construct'\]/, 'HTMT construct labels should come from row_name/row values.')
assert.match(tarkReportTables, /headers: \['Construct', 'Indicator', 'Loading', 'VIF', 'Cronbach’s α', 'rho_A', 'CR', 'AVE'\]/, 'Measurement table should include construct, indicator, loading, VIF, and reliability columns.')
assert.match(tarkReportTables, /headers: \['Hypothesis', 'Path', 'β', 'Mean', 'STDEV', 't-value', 'p-value', '95% CI', 'f²', 'Effect size', 'Decision'\]/, 'Structural table should use the requested journal-ready headings.')
assert.match(tarkReportTables, /TARK_USER_FILL_CELL,\s*\n\s*formatMappedPath/, 'Structural hypothesis cells should be blank for the user to fill after copy.')
assert.match(tarkReportTables, /readPValue\(row\)/, 'Structural table should read p-values through the robust p-value helper.')
assert.match(tarkReportTables, /headers: \['Endogenous construct', 'R²', 'Adjusted R²', 'R² interpretation', 'Q²', 'Q² interpretation'\]/, 'Predictive power table should include blank interpretation columns.')
assert.match(tarkReportTables, /displayFitIndex\(String\(metric\)\)/, 'Model fit rows should display actual fit-index names instead of generic value labels.')
assert.match(tarkReportTables, /function readScalar/, 'Tark report tables should extract scalar values from nested saved-result cells.')
assert.doesNotMatch(tarkReportTables, /if \(typeof value === 'object'\) return '—'/, 'Tark report tables should not discard object-shaped numeric cells.')

console.log('PASS Tark launch static contract')
